# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8ca929ac8759c4f8195498d8186e774a4a61beea10c2b07040a0f2f0ffeb6bcb4899dc74c3f710b2335813db3e2ae95e525c8dba5176434847e699e6d08ca43

test:
  secret_key_base: d1c28a6e197e5a130d9e9262fc8554aa1971784a203d755d859ea22a366f41d5258e14fab817fb941038a50374f7a7ab55ae80c9e29f1738fb2502a44e09cdf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
